"""Reading the corpus index the council writes into the Obsidian vault.

The dashboard is a guest in that file: it is generated by
scripts/build_corpus_index.py from prose reports, so a row can arrive with
stray pipes in it or the whole vault can be offline on an iCloud sync. Nothing
here may raise, because the only caller is a page render.
"""
import os

from dashboard import corpus

FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures", "corpus_index.md")


class TestReadingTheTable:
    def test_every_well_formed_row_becomes_a_ticker(self):
        assert [r["ticker"] for r in corpus.load(FIXTURE)] == \
            ["FLO", "TCEHY", "ACN", "INTC", "DNP.WA"]

    def test_the_file_order_is_kept_because_it_is_sorted_by_verdict_then_date(self):
        decisions = [r["decision"] for r in corpus.load(FIXTURE)]
        assert decisions == ["BUY", "BUY", "BUY", "WAIT", "WAIT"]

    def test_a_row_carries_the_verdict_the_way_the_index_prints_it(self):
        row = next(r for r in corpus.load(FIXTURE) if r["ticker"] == "ACN")
        assert row["decision"] == "BUY"
        assert row["delta"] == "NEW"
        assert row["buy_zone"] == "$145–$193"
        assert row["price"] == "$181.35"
        assert row["conviction"] == "Low"
        assert row["date"] == "2026-08-21"
        assert row["runs"] == 1

    def test_held_and_stale_are_flags_not_the_emoji_that_marks_them(self):
        rows = {r["ticker"]: r for r in corpus.load(FIXTURE)}
        assert rows["TCEHY"]["held"] is True and rows["TCEHY"]["stale"] is True
        assert rows["ACN"]["held"] is False and rows["ACN"]["stale"] is False

    def test_the_ticker_link_gives_the_report_file_with_escapes_undone(self):
        rows = {r["ticker"]: r for r in corpus.load(FIXTURE)}
        assert rows["FLO"]["note_file"] == "FLO_Analysis_2026-01-11.md"
        assert rows["DNP.WA"]["note_file"] == "DNP.WA_Analysis 2026-06-21.md"

    def test_a_vote_containing_its_own_pipes_is_read_whole_not_dropped(self):
        row = next(r for r in corpus.load(FIXTURE) if r["ticker"] == "INTC")
        assert row["vote"] == "4 PASS | 1 SELL | 6 WAIT"
        assert row["date"] == "2026-04-17"

    def test_a_row_that_is_not_a_row_is_skipped_rather_than_breaking_the_page(self):
        assert [r["ticker"] for r in corpus.load(FIXTURE)].count("OOPS") == 0

    def test_the_prose_sections_below_the_table_are_not_read_as_rows(self):
        assert all(r["ticker"] not in ("Ticker", "BUY") for r in corpus.load(FIXTURE))


def _row(ticker, decision="BUY", date="2026-01-01", runs=1):
    return {"ticker": ticker, "decision": decision, "date": date, "runs": runs}


class TestSortingTheTable:
    """The page asks for a column; the corpus decides what that column means."""

    def test_the_default_column_is_the_date_newest_first(self):
        assert [r["ticker"] for r in corpus.sort_rows(corpus.load(FIXTURE), None, None)] == \
            ["ACN", "DNP.WA", "INTC", "TCEHY", "FLO"]

    def test_asking_for_the_date_ascending_puts_the_oldest_analysis_first(self):
        assert [r["ticker"] for r in corpus.sort_rows(corpus.load(FIXTURE), "date", "asc")] == \
            ["FLO", "TCEHY", "INTC", "DNP.WA", "ACN"]

    def test_tickers_sort_alphabetically_without_caring_about_case(self):
        rows = [_row("abbv"), _row("ACN"), _row("Zm")]
        assert [r["ticker"] for r in corpus.sort_rows(rows, "ticker", "asc")] == ["abbv", "ACN", "Zm"]

    def test_the_ticker_column_flips_to_reverse_alphabetical(self):
        assert [r["ticker"] for r in corpus.sort_rows(corpus.load(FIXTURE), "ticker", "desc")] == \
            ["TCEHY", "INTC", "FLO", "DNP.WA", "ACN"]

    def test_the_decision_column_ranks_by_verdict_not_by_alphabet(self):
        rows = [_row("A", "SELL"), _row("B", "HOLD"), _row("C", "BUY"),
                _row("D", "PASS"), _row("E", "WAIT")]
        assert [r["ticker"] for r in corpus.sort_rows(rows, "decision", "asc")] == \
            ["C", "E", "B", "D", "A"]

    def test_a_verdict_the_council_does_not_use_sorts_below_the_ones_it_does(self):
        rows = [_row("A", "MAYBE"), _row("B", "SELL"), _row("C", "BUY")]
        assert [r["ticker"] for r in corpus.sort_rows(rows, "decision", "asc")] == ["C", "B", "A"]

    def test_rows_sharing_a_verdict_are_broken_by_the_newest_analysis(self):
        assert [r["ticker"] for r in corpus.sort_rows(corpus.load(FIXTURE), "decision", "asc")] == \
            ["ACN", "TCEHY", "FLO", "DNP.WA", "INTC"]

    def test_the_runs_column_counts_down_from_the_most_analyzed(self):
        assert [r["ticker"] for r in corpus.sort_rows(corpus.load(FIXTURE), "runs", None)] == \
            ["DNP.WA", "TCEHY", "ACN", "INTC", "FLO"]

    def test_a_column_that_does_not_exist_falls_back_to_the_date(self):
        rows = corpus.load(FIXTURE)
        assert corpus.sort_rows(rows, "colour", None) == corpus.sort_rows(rows, "date", "desc")

    def test_a_direction_that_is_not_one_falls_back_to_the_column_default(self):
        rows = corpus.load(FIXTURE)
        assert corpus.sort_rows(rows, "ticker", "sideways") == corpus.sort_rows(rows, "ticker", "asc")

    def test_sorting_leaves_the_rows_it_was_given_alone(self):
        rows = corpus.load(FIXTURE)
        before = [r["ticker"] for r in rows]
        corpus.sort_rows(rows, "ticker", "asc")
        assert [r["ticker"] for r in rows] == before


class TestFilteringByDecision:
    def test_one_verdict_keeps_only_the_rows_carrying_it(self):
        assert [r["ticker"] for r in corpus.filter_rows(corpus.load(FIXTURE), "WAIT")] == \
            ["INTC", "DNP.WA"]

    def test_no_verdict_asked_for_means_every_row(self):
        assert len(corpus.filter_rows(corpus.load(FIXTURE), None)) == 5

    def test_a_verdict_the_council_does_not_use_is_ignored_rather_than_emptying_the_page(self):
        assert len(corpus.filter_rows(corpus.load(FIXTURE), "SOON")) == 5


class TestWhenThereIsNoVault:
    def test_a_missing_file_is_an_empty_corpus_not_an_error(self, tmp_path):
        assert corpus.load(tmp_path / "nope.md") == []

    def test_a_directory_where_the_index_should_be_is_also_empty(self, tmp_path):
        assert corpus.load(tmp_path) == []

    def test_a_file_with_no_table_at_all_is_empty(self, tmp_path):
        path = tmp_path / "CORPUS_INDEX.md"
        path.write_text("# nothing here yet\n", encoding="utf-8")
        assert corpus.load(path) == []


class TestStatusLine:
    def test_the_status_counts_the_tickers_and_names_the_build_date(self):
        assert corpus.status(FIXTURE) == "5 tickers, updated 2026-09-05"

    def test_a_missing_index_says_where_it_looked(self, tmp_path):
        missing = tmp_path / "nope.md"
        assert corpus.status(missing) == f"corpus index not found at {missing}"

    def test_an_index_with_no_last_updated_line_still_reports_a_count(self, tmp_path):
        path = tmp_path / "CORPUS_INDEX.md"
        path.write_text(
            "| Ticker | Held | Decision | Δ | Buy Zone | Price | Conv. | Vote | Date | Runs | Stale |\n"
            "| [FLO](FLO.md) |  | **BUY** | NEW | — | — | — | — | 2026-01-11 | 1 |  |\n",
            encoding="utf-8")
        assert corpus.status(path) == "1 tickers"


class TestTheDefaultPath:
    def test_the_default_index_is_the_one_build_corpus_index_writes(self):
        assert corpus.default_path().endswith("/reports/CORPUS_INDEX.md")
